#!/usr/bin/env bash
# This script is displays luck messages for numbers or " Best School"
counter=1
while [ $counter -lt 11 ]; do
    if [ $counter -eq 4 ]
    then
	echo "bad luck"
    elif [ $counter -eq 8 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    (( counter=counter+1  ))
done
