#!/usr/bin/env bash
# Script to display the time for 12 hours and 59 minutes using a while loop

minutes=1
hours=0
while [ $hours -lt 13 ]; 
do
    echo Hour: $hours
    while [ $minutes -lt 60 ]; 
    do
	echo $minutes
	(( minutes+=1 ))
    done
    (( minutes=1 ))
    (( hours+=1 ))
done
